spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8092

eureka:
  client:
    registerWithEureka: true
    serviceUrl: 
      defaultZone: ${EUREKA_SERVER:http://localhost:8083/eureka}
    healthcheck:
      enabled: true


info:
  app:
    name: ${spring.application.name}
